//
//  RENTButtonStyle.h
//  Frameworks demo
//
//  Created by Billy Tobon on 5/31/15.
//  Copyright (c) 2015 AltConf 2015. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface RENTButtonStyle : NSObject

// Drawing Methods
+ (void)drawRentButonWithLabel: (NSString*)label isHighlighted: (BOOL)isHighlighted;

@end
